services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cdi_books
      MYSQL_USER: user1
      MYSQL_PASSWORD: azertycdi
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
